services:
  backend:
    build:
      ./backend
    ports:
      - '8888:8888'
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432' # remove before deployment to prod
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    restart: always

volumes:
  postgres-data: